name: "GitHub Actions Chess"
description: "Play chess in your GitHub repository powered by GitHub Actions"
author: "cschleiden"
branding:
    icon: 'play'
    color: 'orange'
inputs:
  games:
    description: "Glob expression to find games in the current folder, default: **/*.pgn"
    default: "**/*.pgn"
  timeToThink:
    description: "Time for the chess engine to think (in ms), defaults to one second"
    default: 1000
runs:
  using: "node12"
  main: "dist/index.js"
